version: '3'
services:
  database:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: qilletni
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    container_name: qilletni
    image: rubbaboy/qilletni:latest
    ports:
      - "8000:8000"
      - "9090:9090"
    depends_on:
      - database
    links:
      - database
    environment:
      POSTGRES_URL: jdbc:postgresql://database:5432/qilletni
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      HTTP_PORT: 8000
      GRPC_PORT: 9090
      REDIRECT_URL: http://localhost:8000/redirect
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
#      _JAVA_OPTIONS: -Dlogging.level.root=DEBUG
volumes:
  database:
