server:
  port: ${HTTP_PORT}
  servlet:
    context-path: ""
grpc:
  server:
    port: ${GRPC_PORT}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
logging:
  level:
    is.yarr.qilletni: debug
